//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.CarLists = new HashSet<CarList>();
        }
    
        public System.Guid CarID { get; set; }
        public System.Guid ModelID { get; set; }
        public System.Guid MakeID { get; set; }
        public System.Guid CurrencyID { get; set; }
        public decimal Price { get; set; }
        public string BodyStyle { get; set; }
        public long Mileage { get; set; }
        public int Transmission { get; set; }
        public string Engine { get; set; }
        public string Drivetrain { get; set; }
        public string ExteriorColor { get; set; }
        public string InteriorColor { get; set; }
        public string Doors { get; set; }
        public int Conditon { get; set; }
        public Nullable<int> Year { get; set; }
        public string Description { get; set; }
        public string StandardEquipment { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string SmallImage { get; set; }
        public string LargeImage { get; set; }
        public int Status { get; set; }
        public string vin { get; set; }
        public Nullable<System.Guid> VehicleTrimID { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Make Make { get; set; }
        public virtual Model Model { get; set; }
        public virtual ICollection<CarList> CarLists { get; set; }
        public virtual VehicleTrim VehicleTrim { get; set; }
    }
}
