//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTrim
    {
        public VehicleTrim()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public System.Guid VehicleTrimID { get; set; }
        public System.Guid ModelID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual ICollection<Car> Cars { get; set; }
    }
}
